### ISSUE TITLE
Log Entry version 2.2.2.1

### ISSUE THREAD

**Issue by heiler** [JustCarmen/webtrees-theme-justlight#119] opened 2022-06-28 09:46 UTC
Personal data was erased.

[client 137.184.121.0] AH01215: PHP Fatal error:  Uncaught ErrorException: Attempt to read property "name" on null in htdocs/webtrees/modules_v4/jc-theme-justlight/resources/views/layouts/default.phtml:46: htdocs/webtrees/index.php
[client 137.184.121.0] AH01215: Stack trace:: htdocs/webtrees/index.php
 [client 137.184.121.0] AH01215: #0 htdocs/webtrees/modules_v4/jc-theme-justlight/resources/views/layouts/default.phtml(46): Fisharebest\\Webtrees\\Webtrees::Fisharebest\\Webtrees\\{closure}(): htdocs/webtrees/index.php
 [client 137.184.121.0] AH01215: #1 htdocs/webtrees/app/View.php(183): include('...'): htdocs/webtrees/index.php
 [client 137.184.121.0] AH01215: #2 htdocs/webtrees/app/View.php(278): Fisharebest\\Webtrees\\View->render(): htdocs/webtrees/index.php
 [client 137.184.121.0] AH01215: #3 htdocs/webtrees/app/Helpers/functions.php(145): Fisharebest\\Webtrees\\View::make(): htdocs/webtrees/index.php
 [client 137.184.121.0] AH01215: #4 htdocs/webtrees/app/Http/ViewResponseTrait.php(54): view(): htdocs/webtrees/index.php
 [client 137.184.121.0] AH01215: #5 htdocs/webtrees/app/Http/Middleware/HandleExceptions.php(171): Fisharebest\\Webtrees\\Http\\Middleware\\HandleExceptions->viewResponse(): htdocs/webtrees/index.php
 [client 137.184.121.0] AH01215: #6 htdocs/webtrees/app/Http/Middleware/HandleExceptions.php(99): Fisharebest\\Webtrees\\Http\\Middleware\\HandleExceptions->httpExceptionResponse(): htdocs/webtrees/index.php
 [client 137.184.121.0] AH01215: #7 htdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\\Webtrees\\Http\\Middleware\\HandleExceptions->process(): htdocs/webtrees/index.php
 [client 137.184.121.0] AH01215: #8 htdocs/webtrees/app/Http/Middleware/BaseUrl.php(79): Middleland\\Dispatcher->handle(): htdocs/webtrees/index.php
 [client 137.184.121.0] AH01215: #9 htdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\\Webtrees\\Http\\Middleware\\BaseUrl->process(): htdocs/webtrees/index.php
 [client 137.184.121.0] AH01215: #10 htdocs/webtrees/app/Http/Middleware/ReadConfigIni.php(68): Middleland\\Dispatcher->handle(): htdocs/webtrees/index.php
 [client 137.184.121.0] AH01215: #11 htdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\\Webtrees\\Http\\Middleware\\ReadConfigIni->process(): htdocs/webtrees/index.php
 [client 137.184.121.0] AH01215: #12 htdocs/webtrees/app/Http/Middleware/SecurityHeaders.php(48): Middleland\\Dispatcher->handle(): htdocs/webtrees/index.php
 [client 137.184.121.0] AH01215: #13 htdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\\Webtrees\\Http\\Middleware\\SecurityHeaders->process(): htdocs/webtrees/index.php
 [client 137.184.121.0] AH01215: #14 htdocs/webtrees/app/Http/Middleware/EmitResponse.php(57): Middleland\\Dispatcher->handle(): htdocs/webtrees/index.php
 [client 137.184.121.0] AH01215: #15 htdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\\Webtrees\\Http\\Middleware\\EmitResponse->process(): htdocs/webtrees/index.php
 [client 137.184.121.0] AH01215: #16 htdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\\Dispatcher->handle(): htdocs/webtrees/index.php
 [client 137.184.121.0] AH01215: #17 htdocs/webtrees/app/Webtrees.php(275): Middleland\\Dispatcher->dispatch(): htdocs/webtrees/index.php
 [client 137.184.121.0] AH01215: #18 htdocs/webtrees/app/Webtrees.php(262): Fisharebest\\Webtrees\\Webtrees::dispatch(): htdocs/webtrees/index.php
 [client 137.184.121.0] AH01215: #19 htdocs/webtrees/index.php(51): Fisharebest\\Webtrees\\Webtrees->httpRequest(): htdocs/webtrees/index.php
 [client 137.184.121.0] AH01215: #20 {main}: htdocs/webtrees/index.php
 [client 137.184.121.0] AH01215:   thrown in htdocs/webtrees/modules_v4/jc-theme-justlight/resources/views/layouts/default.phtml on line 46: htdocs/webtrees/index.php

**Comment by mpwt** [comment] 2022-08-25 13:37
I found the same error message in an error log file in the root folder of webtrees. Could it be that this has something to do with PHP 8 or 8.1? I got the error message only after switching to webtrees 2.1.7 and PHP 8.1?

**Comment by JustCarmen** [comment] 2022-08-25 13:59
I think this should fix it.

**Comment by mpwt** [comment] 2022-08-30 16:24
Thank you. 

Nearly. Now there is the following error message in the error_log file:

[30-Aug-2022 15:49:48 UTC] PHP Fatal error:  Uncaught Fisharebest\Webtrees\Http\Exceptions\HttpBadRequestException: Der Parameter „route“ fehlt. in [replaced]/app/Validator.php:318
Stack trace:
#0 [replaced]/modules_v4/jc-theme-justlight/resources/views/layouts/default.phtml(47): Fisharebest\Webtrees\Validator->route()
#1 [replaced]/app/View.php(183): include('/home/bauschaf/...')
#2 [replaced]/app/View.php(278): Fisharebest\Webtrees\View->render()
#3 [replaced]/app/Helpers/functions.php(145): Fisharebest\Webtrees\View::make()
#4 [replaced]/app/Http/ViewResponseTrait.php(54): view()
#5 [replaced]/app/Http/Middleware/HandleExceptions.php(171): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->viewResponse()
#6 [replaced]/app/Http/Middleware/HandleExceptions.php(99): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->httpExceptionResponse()
#7 [replaced]/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->process()
#8 [replaced]/app/Http/Middleware/BaseUrl.php(79): Middleland\Dispatcher->handle()
#9 [replaced]/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl->process()
#10 [replaced]/app/Http/Middleware/ReadConfigIni.php(68): Middleland\Dispatcher->handle()
#11 [replaced]/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process()
#12 [replaced]/app/Http/Middleware/SecurityHeaders.php(48): Middleland\Dispatcher->handle()
#13 [replaced]/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders->process()
#14 [replaced]/app/Http/Middleware/EmitResponse.php(57): Middleland\Dispatcher->handle()
#15 [replaced]/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process()
#16 [replaced]/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle()
#17 [replaced]/app/Webtrees.php(275): Middleland\Dispatcher->dispatch()
#18 [replaced]/app/Webtrees.php(262): Fisharebest\Webtrees\Webtrees::dispatch()
#19 [replaced]/index.php(51): Fisharebest\Webtrees\Webtrees->httpRequest()
#20 {main}
  thrown in [replaced]/app/Validator.php on line 318

**Comment by JustCarmen** [comment] 2022-09-01 07:55
I am unable to reproduce this error. A few questions:
- Does this error occur on every page or not?
- If not, do you know which page you viewed when the error occurs. 
- Do you have the same error when using the default webtrees theme?

**Comment by mpwt** [comment] 2022-09-05 12:05
Thank you very much for your effort. It seems to have nothing to do with the theme -> https://github.com/fisharebest/webtrees/issues/4548.

**Comment by JustCarmen** [comment] 2022-09-06 17:49
Thanks for your response. Since this is not an issue with this theme, I will close this issue now.

**Closed by JustCarmen** 2022-09-06 17:49 UTC
