### ISSUE TITLE
Maps are no longer displayed with v2.3.0 @ webtrees 2.2

### ISSUE THREAD

**Issue by TheRealJPS** [JustCarmen/webtrees-theme-justlight#181] opened 2024-12-08 22:33 UTC
See e.g. ...

https://ahnen.familie-stern.de/tree/stern/place-list/0?action2=list
https://ahnen.familie-stern.de/tree/stern/individual/I4174/Henne-Meyer#tab-places

It works with the XENEA theme.

**Comment by JustCarmen** [comment] 2024-12-09 10:26
I cannot reproduce this problem. The maps load normally on my test system. What map provider are you using? Does switching to another provider help? I use OpenStreetmap.

Could you please disable all custom modules and tell me if the problem still exists? There may be a conflict with another module.

**Comment by TheRealJPS** [comment] 2024-12-09 11:06
Hi thanks,

I use OpenStreetmap as well, but I tested it with GoogleMaps -> same.

Now I have deactivated all modules one by one, except for...
![2](https://github.com/user-attachments/assets/0698a9ca-ab67-4a2e-ada6-b44a76d6354b)

...and deleted the following modules (except "jc-theme-justlight")...
![4](https://github.com/user-attachments/assets/96ad5da5-6e88-44b1-8a86-e80b4ea2fc94)

Still the same...
![1](https://github.com/user-attachments/assets/fec35b1f-cdac-4ba1-afd3-7a4137e003ac)

**Comment by JustCarmen** [comment] 2024-12-09 11:40
Okay, clear. Thanks. I had to rule out a possible conflict with other modules. But it seems to be just a problem with the JustLight theme. Unfortunately, I can't reproduce it, which makes it hard to fix. At the moment I have no idea. I have to go now, but I will investigate this further as soon as I have time.

You can re-enable the modules and get your site back to its original state. You might want to set the Xenea theme as default for now. But keep the Justlight theme available so I can investigate this issue further.

**Comment by pieterbultena** [comment] 2024-12-10 09:07
I have the same problem. Page 'Place hierarchy' does not work and also the map on individual pages does not pop-up. See [this](https://bultena.eu/index.php?route=%2Ftree%2Fbultena%2Findividual%2FI2%2FWillem-Bultena#tab-places) example. 

I use OpenStreetMaps and only the JustLight plug-in.

**Comment by gudjonsi** [comment] 2024-12-10 18:04
I'm experiencing the same problem, i.e. continuous spinning wheel displayed when either selecting the Pedigree Map under Charts or Places Tap on an Individual page. The problem appears to be only tied to the JustLight theme version 2.3.0. Themes tested without experiencing this problem: clouds, colours, F.A.B., minimal, Primer, webtrees and xenea. This was tested on both local installatiion of webtrees version 2.2.1 (Server PHP Versions 8.3) and online installation of webtrees version 2.2.1 (Server PHP Versions 8.3). OpenStreetMap Map Service was selected and has worked without any problems previously with the JustLight Theme. This was tested on the following browsers with the same result: Firefox, Safari and Chrome. Best regards.

**Comment by JustCarmen** [comment] 2024-12-10 20:06
Hi everyone, thanks for reporting the problem. I haven't found a solution yet. I am still searching, but luckily I was able to produce the error on my live site. Everything works fine on my local test site. I haven't figured out why. 

On my live site I am still on php 8.2. Moving to php 8.3 will be later this week or next week according to my host. This means that the bug is not only related to webtrees 2.2 (justlight 2.3.0) but exists in the version for webtrees 2.1 too (justlight 2.2.9).

The error I get in my console log, and I saw this at the site of the @TheRealJPS too, is this:
`VM152:17 Uncaught TypeError: L.markerClusterGroup is not a function
    at <anonymous>:17:21
    at <anonymous>:118:5
    at L (vendor.min.js?v=2.1.22:2:426619)
    at Zt (vendor.min.js?v=2.1.22:2:471992)
    at k.fn.init.append (vendor.min.js?v=2.1.22:2:473202)
    at k.fn.init.<anonymous> (vendor.min.js?v=2.1.22:2:474306)
    at tt (vendor.min.js?v=2.1.22:2:455067)
    at k.fn.init.html (vendor.min.js?v=2.1.22:2:473982)
    at Evert-Laurens-Andrew-Romeo-Bang-A-Foe:4909:32`

But I haven't figured out the cause of this error. I am still searching.

**Comment by TheRealJPS** [comment] 2024-12-10 20:32
If it helps, I'm using PHP 8.4.1. For testing I switched to PHP 8.3.13, but no effect. With PHP 8.2, webtrees 2.2.1 logically shows "Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.3.0"." Now I'm back to 8.4.1.

**Closed** 2024-12-12 20:22 UTC

**Comment by JustCarmen** [comment] 2024-12-12 20:25
It turned out to be a conflict with the latest update of Fontawesome script. This script is used for some icons in the theme. I downgraded the package to the latest working version and now the maps are displaying properly.

This is not a permanent solution, but for now the best I can do.

I have released two new versions. One for the wt-2.1 branche and one for wt-2.2.

**Comment by JustCarmen** [comment] 2024-12-15 10:12
Using a customized FontAwesome library with just the icons we need, will help to reduce conflicts with other vendor scripts. (f8925349af2dce761f8edb0fc7adbc14d766662f). This is a better solution.
