### ISSUE TITLE
missing icon ?

### ISSUE THREAD

**Issue by arbor95** [JustCarmen/webtrees-theme-justlight#102] opened 2022-02-12 09:11 UTC
seems as if missing
![missing](https://user-images.githubusercontent.com/6124739/153705162-b171ee77-7085-4047-8a92-c123b996d19b.jpg)
on the "my page"

**Comment by JustCarmen** [comment] 2022-02-12 14:28
It seems that not all files from the latest release have been uploaded to your server.

Please check if the following files exist:
- resources\js\fa-regular.min.js
- resources\js\fa-solid.min.js

**Comment by JustCarmen** [comment] 2022-02-13 08:40
Maybe you should clear your browser cache and delete the folder data/cache.

I have created a new [release](https://github.com/JustCarmen/webtrees-theme-justlight/releases/tag/2.1.2.3) that fixed some other problems with this release. It's worth trying.

If this doesn't help, could you please give me a link to your website so I can take a look?

**Comment by JustCarmen** [comment] 2022-02-13 11:35
> the site is https://freris.de/ where to send you a login?

You accidentally posted your answer in the wrong issue.

But to answer your question. I went to your homepage and the first thing I saw when looking in the chrome console is a javascript error which has nothing to do with the Justlight theme, but is probably the cause the scripts in the Justlight theme stopped working.

![image](https://user-images.githubusercontent.com/5641963/153751100-ff72d12e-5f30-45ec-b7b4-57d1f81263be.png)

The error is in a module named 'Argon'. Deactivate this module to see if it solves your problem with the Justlight theme.

**Comment by JustCarmen** [comment] 2022-02-13 16:03
I cannot reproduce this error. You are using different custom modules. Disable them all (except Justlight), remove your cache and check if it solves the problem.

If that doesn't help email me the login credentials so I can investigate it further. You'll find my email address in my profile.

**Comment by arbor95** [comment] 2022-02-13 17:19
Thanks for your investigations.
The conflicting module is the "vesta_classic_look_and_feel".
Tell me what I can do further to solve this conflict.

**Comment by arbor95** [comment] 2022-02-14 08:30
I wonder. At my page I still can reproduce the error, simply by enabling Vesta LAF  and vice versa with .disable having correct representation by simply refreshing the page.

**Comment by arbor95** [comment] 2022-02-14 08:57
so following setting of Vesta LAF is responsible for the error:
![checkbox-producing-error](https://user-images.githubusercontent.com/6124739/153831747-629e92ee-a77e-4502-89f2-ad55df7d0f09.jpg)

**Comment by JustCarmen** [comment] 2022-02-14 11:57
It doesn't make sense. The feature you turned on has nothing to do with the 'user welcome block' at 'my page'. But of course I've tried it in my test system, but even if I turn on the same options as you mentioned above, I still can't reproduce the error.

What browser are you using? Do you see any error messages in your website logs?

Otherwise give me (temporary) access to your site, to investigate it further. But I think I need admin access to help you with this. So it is up to you whether you are comfortable with that.

**Comment by JustCarmen** [comment] 2022-02-14 15:35
I've found the problem. The module Vesta Classic LAF determine if the Justlight theme is loaded depending on the support url.

Since I've changed the support url in the latest release, the layout for the Justlight theme which effects the footer scripts were not loaded. These footer scripts are responsible for loading the custom icons.

I've done a [pull request](https://github.com/vesta-webtrees-2-custom-modules/vesta_classic_laf/pulls) in vesta_classic_laf which fixes this issue.

You can either wait for Richard to release a new version of the Classic LAF module or manual make the changes to the file ClassicLAFModule.php for the time being. View the pull request to see the changes.

I will close this issue now, since it is up to Richard to make the changes in his module.

**Closed by JustCarmen** 2022-02-14 15:35 UTC
